MODEL: "NB"
TUNE_HP_PARAMS: False
NB:
  # -----------------------------------------------------------------------------
  # Gaussian Naive Bayes
  # For full documentation, please see:
  # https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html
  # -----------------------------------------------------------------------------
  priors: null
  var_smoothing: 1e-08

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: True

OUTPUT_DIR: "./output"
