MODEL: "RF"
TUNE_HP_PARAMS: True
RF:
  # -----------------------------------------------------------------------------
  # Random Forest
  # For full documentation, please see:
  # https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
  # -----------------------------------------------------------------------------
  n_estimators: [10, 100, 1000]
  criterion: ["gini", "entropy"]
  max_depth: [None, 10, 20, 30]
  min_samples_split: [2, 4, 6]
  min_samples_leaf: [1, 2, 3]
  max_features: ["auto", "sqrt", "log2"]
  n_jobs: [-1]
  ccp_alpha: [0.0, 0.2, 0.4, 0.6]
  random_state: [null]

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: False

OUTPUT_DIR: "./output"
