MODEL: "MLP"
TUNE_HP_PARAMS: False
MLP:
  # -----------------------------------------------------------------------------
  # Multilayer Perceptron
  # For full documentation, please see:
  # https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html
  # -----------------------------------------------------------------------------
  hidden_layer_sizes: [300, 300]
  activation: "tanh"
  solver: "sgd"
  learning_rate: "adaptive"
  max_iter: 200
  # random_state: 0
  n_iter_no_change: 200
  batch_size: "auto"

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: True

OUTPUT_DIR: "./output"
