MODEL: "MLP"
TUNE_HP_PARAMS: True
MLP:
  # -----------------------------------------------------------------------------
  # Multilayer Perceptron
  # For full documentation, please see:
  # https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html
  # -----------------------------------------------------------------------------
  hidden_layer_sizes: [[300], [300, 300], [300, 150]]
  activation: ["logistic", "tanh", "relu"]
  solver: ["lbfgs", "sgd", "adam"]
  # alpha: [0.1, 0.01, 0.001, 0.0001, 0.00001]
  learning_rate: ["adaptive"]
  # learning_rate_init: [0.001]
  max_iter: [200]
  random_state: [null]
  n_iter_no_change: [200]
  batch_size: ["auto"]

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: False

OUTPUT_DIR: "./output"
